services:
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    container_name: amarshop_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=amarshop_db
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=123456

volumes:
  postgres_data:
