# Generated by Django 5.0.6 on 2025-01-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='student_name')),
                ('stu_class', models.IntegerField(verbose_name='student_class')),
            ],
        ),
    ]
